### ISSUE TITLE
Initial setup: no root password asked, passwd complains

### ISSUE THREAD

**Issue by BioMike** [flavioc/cross-hurd#17] opened 2022-11-29 09:25 UTC
In the initial setup script, passwd is called for entering a root password (at least I think the script tries to do this). However, the setup script doesn't wait and just continues. passwd complains about a too short password, but accepts what's being done at that stage. The setup continues and reboots in the new system. At the end the login prompt is given and one can login as root with an empty password.

I don't think the script works here as intended, but I can be mistaken.

Expected solution: setup script waits for the user to enter a root password and passwd can set that. After that the setup script continues.

**Comment by flavioc** [comment] 2022-12-08 07:21
Should be fixed with the last commit. The issue was caused by the devices not being setup before asking for user input.

**Closed by flavioc** 2022-12-08 07:21 UTC
